### ISSUE TITLE
Resizable Handle prebuilt styles

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#351]
**Is your feature request related to a problem? Please describe.**
There's been a design request from my team for the second time and on different apps to have the resizable handle visible with a border style. I had to build this with a very ugly CSS workaround.

**Describe the solution you'd like**
A prebuilt style for the Resizable handle. I can't think of other than the border style that might be needed at the moment.

**Describe alternatives you've considered**
At the moment this is how I use vertical (first one) and horizontal (second one) resizable handles with border style.

```scss
// Resizables with divider style
#codemirror-resizable div[class*='_handle_']:nth-of-type(2) {
	opacity: 1;
	&::before {
		transition: opacity 0.3s;
		background: linear-gradient(to right, transparent, var(--rs-color-border-neutral), transparent);
		background-size: 1px 100%;
		background-position: center;
		background-repeat: no-repeat;
	}
	&:hover {
		&::before {
			opacity: 0;
		}
	}
}

div[class*='_handle_']:not(#codemirror-resizable div[class*='_handle_']) {
	opacity: 1;
	&::before {
		transition: opacity 0.3s;
		background: linear-gradient(to bottom, transparent, var(--rs-color-border-neutral), transparent);
		background-size: 100% 1px;
		background-position: center;
		background-repeat: no-repeat;
	}
	&:hover {
		&::before {
			opacity: 0;
		}
	}
}
```
