### ISSUE TITLE
[Low Priority] Border props for View component

### ISSUE THREAD

**Issue by egucciar** [formaat-design/reshaped#429]
**Is your feature request related to a problem? Please describe.**
I need a way to set borders only on one side of view

**Describe the solution you'd like**
Will show the "wrapped" solution I created as the possible solution

**Describe alternatives you've considered**
Continue to use my custom wrapper

**Additional context**
My custom wrapper code:

```tsx
import React from "react";
import {View as ReshapedView, type ViewProps as ReshapedViewProps} from "reshaped";

import {classNames} from "@ob/common/lib/ClassNames";

import styles from "./View.module.scss";

export interface ViewProps extends ReshapedViewProps {
    borderTop?: boolean;
    borderBottom?: boolean;
    borderLeft?: boolean;
    borderRight?: boolean;
    borderVertical?: boolean;
    borderHorizontal?: boolean;
}

export const View = ({
    className,
    borderTop,
    borderBottom,
    borderLeft,
    borderRight,
    borderVertical,
    borderHorizontal,
    ...props
}: ViewProps) => {
    const viewClassName = classNames(
        {
            [styles.borderTop]: borderTop,
            [styles.borderBottom]: borderBottom,
            [styles.borderLeft]: borderLeft,
            [styles.borderRight]: borderRight,
            [styles.borderVertical]: borderVertical,
            [styles.borderHorizontal]: borderHorizontal,
        },
        className
    );

    return <ReshapedView className={viewClassName} {...props} />;
};

View.displayName = "View";
View.Item = ReshapedView.Item;
```

```scss
.borderTop {
  border: unset;
  border-top: 1px solid var(--rs-border-color);
}
.borderBottom {
  border: unset;
  border-bottom: 1px solid var(--rs-border-color);
}
.borderLeft {
  border: unset;
  border-left: 1px solid var(--rs-border-color);
}
.borderRight {
  border: unset;
  border-right: 1px solid var(--rs-border-color);
}
.borderVertical {
  border: unset;
  border-left: 1px solid var(--rs-border-color);
  border-right: 1px solid var(--rs-border-color);
}
.borderHorizontal {
  border: unset;
  border-top: 1px solid var(--rs-border-color);
  border-bottom: 1px solid var(--rs-border-color);
}
```
